# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customer_window(object):
    def setupUi(self, customer_window):
        customer_window.setObjectName("customer_window")
        customer_window.resize(628, 445)
        self.verticalLayout = QtWidgets.QVBoxLayout(customer_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(customer_window)
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.admin_button = QtWidgets.QPushButton(self.top_frame)
        self.admin_button.setObjectName("admin_button")
        self.horizontalLayout.addWidget(self.admin_button)
        self.verticalLayout.addWidget(self.top_frame)
        self.bottom_frame = QtWidgets.QFrame(customer_window)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.verticalLayout.addWidget(self.bottom_frame)

        self.retranslateUi(customer_window)
        QtCore.QMetaObject.connectSlotsByName(customer_window)

    def retranslateUi(self, customer_window):
        _translate = QtCore.QCoreApplication.translate
        customer_window.setWindowTitle(_translate("customer_window", "Form"))
        self.admin_button.setText(_translate("customer_window", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    customer_window = QtWidgets.QWidget()
    ui = Ui_customer_window()
    ui.setupUi(customer_window)
    customer_window.show()
    sys.exit(app.exec_())
