# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_Window(object):
    def setupUi(self, main_Window):
        main_Window.setObjectName("main_Window")
        main_Window.resize(1155, 912)
        main_Window.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.central_widget = QtWidgets.QWidget(main_Window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_frame = QtWidgets.QFrame(self.central_widget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3.addWidget(self.main_frame)
        main_Window.setCentralWidget(self.central_widget)
        self.status_bar = QtWidgets.QStatusBar(main_Window)
        self.status_bar.setObjectName("status_bar")
        main_Window.setStatusBar(self.status_bar)

        self.retranslateUi(main_Window)
        QtCore.QMetaObject.connectSlotsByName(main_Window)

    def retranslateUi(self, main_Window):
        _translate = QtCore.QCoreApplication.translate
        main_Window.setWindowTitle(_translate("main_Window", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_Window = QtWidgets.QMainWindow()
    ui = Ui_main_Window()
    ui.setupUi(main_Window)
    main_Window.show()
    sys.exit(app.exec_())
